### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [HQAnime/AnimeOne#30]
Could you please publish this app on F-Droid?

**Comment by HenryQuan** [comment]
I can but I don't know how and if this app follows its guideline.

**Comment by linsui** [comment]
I'll do that. Thanks!

**Comment by linsui** [comment]
Done. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10519 Is there anything you'd like to add, e.g. donation infomation?

**Comment by HenryQuan** [comment]
Ohh, that's quick, thank you. The donation is https://www.paypal.me/yihengquan. It is also available in app so it should be fine. I will review your pull request and probably, it can be merged soon.

**Comment by linsui** [comment]
F-Droid will update your app automatic when you tag a new release. But please make sure that the version code in https://github.com/HQAnime/AnimeOne/blob/52d57d2a5cec3be59b0b1b4b6d892a39cf8adfc2/animeone/pubspec.yaml#L14 is increased for every release. If I understand correctly, it only checks update when user tapping the button. This is OK.

**Comment by HenryQuan** [comment]
The app actually checks for update once every week automatically but the user can choose to update if an new version is available. I need to double check on this. However, the downloading is triggered by the user.

**Comment by linsui** [comment]
We can patch it for F-Droid in the build metadata.

**Comment by HenryQuan** [comment]
https://github.com/HQAnime/AnimeOne/blob/c20f2a8e4f1ec98e17cdffbe1d192fe47ed70b66/animeone/lib/ui/page/home.dart#L41
This is where the update is pulled.

**Comment by linsui** [comment]
I guess I just need to remove Line 42. I'll test it, thanks!

**Comment by HenryQuan** [comment]
Is it possible to also release it on GitHub as well. like having two different builds? Most of users may not be using f-droid at all.

**Comment by linsui** [comment]
Do you mean  releasing the apk built by F-Droid on GitHub? Yes, of course!

**Comment by HenryQuan** [comment]
I want to keep the auto update for the GitHub while having a special build for F-Droid. I may need to add a new variant and build with fastlane instead.

**Comment by linsui** [comment]
Does [this](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10519/diffs#22c36e9afabbcf7f6748cad784ebad06fbab94e6_0_33) work? If this is enough to disable update check then we can merge it and no need to add a flavor. Thanks!

**Comment by HenryQuan** [comment]
We can simply remove that line to disable the alert but I don't know how this works. Does F-Droid build the app automatically and sign it? If so, I think it should be fine.

**Comment by linsui** [comment]
Yes, F-Droid builds apk from source and sign it. Then I'll merge it. Thanks!

**Comment by HenryQuan** [comment]
Thank you so much for the help.

**Comment by linsui** [comment]
Forgot to say, if you'd like to, you can put this in the readme. :smile: 

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/org.github.henryquan.animeone)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/org.github.henryquan.animeone)
```

**Comment by HenryQuan** [comment]
Ohhh fancy. I will put it for sure.
