### ISSUE TITLE
Could you please bump the version code for every release?

### ISSUE THREAD

**Issue by linsui** [HQAnime/AnimeOne#36]
F-Droid check new versions with the version code so that if the version code is always 1 F-Droid can't update it. Thanks!

**Comment by HenryQuan** [comment]
Sorry, there seems to be a problem with the version. I will update it.

**Comment by linsui** [comment]
Thanks!

**Comment by HenryQuan** [comment]
I have fixed the build number. It should be 115 now instead of 1.

**Comment by linsui** [comment]
Thanks! I'll update the F-Droid build metadata.
