### ISSUE TITLE
沒有找到動畫鏈接？

### ISSUE THREAD

**Issue by AngelofMe** [HQAnime/AnimeOne#45]
https://pekora.v.anime1.me/1043/12b.mp4
https://gura.v.anime1.me/1039/12b.mp4
https://fubuki.v.anime1.me/1006/16.mp4
https://korone.v.anime1.me/993/24b.mp4
https://shiro.v.anime1.me/1016/13b.mp4
https://fubuki.v.anime1.me/1014/24b.mp4
https://korone.v.anime1.me/1038/11b.mp4
https://aqua.v.anime1.me/1034/12b.mp4

**Comment by HenryQuan** [comment]
This is now fixed in deddcc6. Thx for the issue.
